set_property SRC_FILE_INFO {cfile:{C:/khris/大二上/Logic-Design-Laborator/Keyboard_and_Audio_Sample_Code/Unit9_demo2_music box/constraints.xdc} rfile:{C:/khris/大二上/Logic-Design-Laborator/Keyboard_and_Audio_Sample_Code/Unit9_demo2_music box/constraints.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports pmod_1]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports pmod_2]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports pmod_4]
